#!/bin/sh
git --work-tree=/var/www/html/wp-content/themes/schoolsite/ --git-dir=/var/www/html/wp-content/themes/schoolsite/ checkout -f
git --work-tree=/var/www/html/wp-content/themes/schoolsite/ --git-dir=/var/www/html/wp-content/themes/schoolsite/ pull
echo "Hooray, the new version is published!"